spring:
  profiles:
    active: dev
  application:
    name: sso-backend
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: msa-service

allowed:
  origin: ${ALLOWED_ORIGIN}

server:
  port: 8087
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

keycloak:
  server-url: ${KEYCLOAK_URL}
  realm: hubilon_pd
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  secure-cookie: false                      # 로컬 HTTP 개발 시 false, HTTPS 배포 시 true
  access-token-cookie: _a_t         # access token 쿠키 이름 (기본값: access_token)
  refresh-token-cookie: _r_t       # refresh token 쿠키 이름 (기본값: refresh_token)
  redirect-uri: ${KEYCLOAK_REDIRECT_URI}          # 콜백 URL (각 서비스마다 다르게)
  post-login-redirect-uri: ${KEYCLOAK_POST_LOGIN_REDIRECT_URI}               # 로그인 후 이동 경로
  post-logout-redirect-uri: ${KEYCLOAK_POST_LOGOUT_REDIRECT_URI}  # 로그아웃 후 이동할 URL
  additional-scopes: # openid, profile은 자동 포함
    - email                 # 기본값 (생략 가능)
  auth-controller:
    enabled: true
  permit-all-paths:
    - /public/**
    - /health
    - /actuator/**
    - /api-docs/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /api/v1/auth/login
    - /api/v1/auth/register
    - /api/v1/auth/public-key

