spring:
  profiles:
    active: dev
  application:
    name: sso-backend
  datasource:
    url: jdbc:postgresql://192.168.10.30:6543/hubilon_pd
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: msa-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  redirect-uri: ${KEYCLOAK_REDIRECT_URI}

cookie:
  secure: ${COOKIE_SECURE:false}

allowed:
  origin: ${ALLOWED_ORIGIN:http://localhost:5173}

server:
  port: 8080
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
